<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>DTOs</AssemblyName>
		<RootNamespace>DTOs</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Entity\Entity.csproj" />
	</ItemGroup>
</Project>