// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class Category
{
    public int CatogeryId { get; set; }

    public string CatogeryName { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}