// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class Catogery
{
    public int Id { get; set; }

    public string CatogeryName { get; set; }
}