// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entity;

public partial class Product
{
    public int Id { get; set; }

    public int? CatogeryId { get; set; }

    public string ProductName { get; set; }

    public string DescreptionProduct { get; set; }

    public int? Price { get; set; }

    public string Path { get; set; }
}