// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entity;

namespace Repository;

public partial class Store_329391924Context : DbContext
{
    public Store_329391924Context(DbContextOptions<Store_329391924Context> options)
        : base(options)
    {
    }

    
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<Catogery> Catogeries { get; set; }
    public virtual DbSet<Product> Products { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Catogery>(entity =>
        {
            entity.HasNoKey();
            entity.Property(e => e.CatogeryName)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("Catogery_Name");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasNoKey();
            entity.Property(e => e.CatogeryId).HasColumnName("Catogery_ID");
            entity.Property(e => e.DescreptionProduct)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("Descreption_Product");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Path)
                .HasMaxLength(20)
                .IsFixedLength();
            entity.Property(e => e.ProductName)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("Product_Name");
        });



        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Email)
                .HasMaxLength(25)
                .IsFixedLength();
            entity.Property(e => e.FirstName)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("First_Name");
            entity.Property(e => e.LastName)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("Last_Name");
            entity.Property(e => e.Password)
                .HasMaxLength(30)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}